{
 "title": "Main dashboard",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "query": "artillery-api" },
   {
    "name": "container",
    "query": "tp_arqui-node-1, tp_arqui-node-2, tp_arqui-node-3"
   }
  ]
 },
 "panels": [
  {
   "title": "Scenarios launched (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$server.scenarioCounts.*)"
    }
   ]
  },
  {
   "title": "Requests state (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$server.errors.*), 'Errored')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.200, 'Completed')"
    },
    {
     "target": "alias(stats.gauges.$server.pendingRequests, 'Pending')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.429, 'Limited')"
    }
   ]
  },
  {
   "title": "Response time (client-side)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.max, 'Upper')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.median, 'Median')"
    }
   ]
  },
  {
   "title": "Response time (client-side)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.nodeapi.external_api_time, 'external')"
    },
    {
     "target": "alias(stats.gauges.nodeapi.complete_time, 'complete_time')"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.$container.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.$container.memory_working_set, 34359738368), 'Memory')"
    }
   ]
  }
 ]
}